title: Computer Organization with Logisim
baseurl: "/computer-organization-logisim"
url: "https://mkayaalp.net"
git_repository_url: "https://github.com/mkayaalp/computer-organization-logisim"
edit_url_template: "https://github.com/mkayaalp/computer-organization-logisim/edit/main/docs/[path]"

prologues:
  - path: index.md
  - path: chapters/getting-started.md
chapters:
  - path: chapters/logic-design-review.md
    sections:
      - path: chapters/combinational.md
      - path: chapters/sequential.md
      - path: chapters/synchronous.md
      - path: chapters/propagation-clock.md
      - path: chapters/tristate.md
  - path: chapters/combinational-vs-pipelined-multiplier.md

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
